version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://root:1234@db:3306/contactos_crud
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
  db:
    image: mariadb:10.6
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=contactos_crud
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    networks:
      - app-network
volumes:
  mariadb_data:
networks:
  app-network:
    driver: bridge